#!/bin/bash

if [ "$1" == "update" ]; then
	echo -ne updating dbash script...
	script="$0"
	basename="$(dirname $script)"

	wget https://raw.githubusercontent.com/Nasty/dbash/master/dbash -O /tmp/dbash &>/dev/null
        cat /tmp/dbash > $basename/dbash
        rm /tmp/dbash
	echo " done"
	exit
fi

skipSelection=false

if [ $# -gt 0 ]; then
	skipSelection=true
	hash=$1
fi

if [ "$skipSelection" = false ]; then
	OUTPUT="$(docker ps)"
	lines=0
	while read -r line; do
		if [ "$lines" -gt 0 ]; then
			echo "[$lines] $line ..."
		fi
		lines=$((lines+1))
	done <<< "$OUTPUT"

	if [ "$lines" -eq 2 ]; then
		echo
		echo Select docker container: 1
		selection=1
	else
		echo
		echo Select docker container:
		read selection
	fi

	lines=0
	regex='^([0-9a-z])'

	while read -r line; do
		if [ "$lines" -eq "$selection" ]; then
			hash=$(echo $line | cut -c1-12)
		fi
		lines=$((lines+1))
	done <<< "$OUTPUT"
fi

docker exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" -it $hash bash
